name: gh-pages publisher 🚀

on:
push:
    branches: [master]

jobs:
build:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-python@v2
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install sphinx_rtd_theme
    - name: Install requirements
        with:
          requirements: src/requirements.txt
    - name: Build website
        run: make github_action_docs
    - name: Commit and Push
        run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
        # use account 'github-actions[bot]' to set the git config
        git add docs
        git commit -m "new github pages"
        git push